#!/bin/bash

# Function to display subdomain information
display_info() {
	local domain=$1
	local subdomain=$2

	if [[ -z $subdomain ]]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomains=($subdomain)
	fi

	for sub in "${subdomains[@]}"; do
		result=$(dig +short "$sub"."$domain")
		record_type="A"
		destination=$(echo "$result")
		echo "The subdomain $sub is a $record_type record and points to $destination"
	done
}

# Main script
if [[ $# -lt 1 ]]; then
	echo "Usage: $0 <domain> [subdomain]"
	exit 1
fi

domain=$1
subdomain=$2

display_info "$domain" "$subdomain"
