#!/usr/bin/env bash
# Sets up Nginx on a new Ubuntu machine

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sed -i -e "/server_name _;/ {
        N
        s/server_name _;/server_name _;\\n\\n\
\\tlocation \\/redirect_me {\\n\
\\t\\treturn 301 https:\\/\\/www.youtube.com\\/watch?v=QH2-TGUlwu4;\\n\
\\t}/
        p
        x
}" /etc/nginx/sites-enabled/default

service nginx start
