#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
# Update package lists and install nginx
apt-get -y update
apt-get -y install nginx

# Set the hostname to a variable
HOSTNAME=$(hostname)

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Add redirection and custom header configuration to Nginx default site configuration
sed -i "/server_name _;/a \ \trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4;\n \ \terror_page 404 /custom_404.html;\n \ \tlocation = /custom_404.html {\n \ \t\troot /usr/share/nginx/html;\n \ \t\tinternal;\n \ \t}" /etc/nginx/sites-available/default
sed -i "/include \/etc\/nginx\/sites-enabled\/\*;/a \ \tadd_header X-Served-By \"$HOSTNAME\";" /etc/nginx/nginx.conf

# Restart Nginx
service nginx restart

