#!/usr/bin/env bash

# Install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Enable HAProxy service
echo "ENABLED=1" > /etc/default/haproxy

# Append configuration to haproxy.cfg
echo "
frontend load_balancer
        bind *:80
        mode http
        default_backend servers

backend servers
        balance roundrobin
        server 421688-web-01 54.175.87.70:80 check
        server 421688-web-02 3.84.255.47:80 check" >> /etc/haproxy/haproxy.cfg

sudo ufw allow 80/tcp
# Start HAProxy service
sudo service haproxy start
