#!/usr/bin/env bash
# Installs and setup haproxy

# Listen to web1 and web2 servers
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 421688-web-01 54.175.87.70:80 check
   server 421688-web-02 3.84.255.47:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
