#!/usr/bin/env bash
# Backup and compress all MySQL databases

# Get the current date in the desired format
backup_date=$(date +%d-%m-%Y)

# Create the MySQL dump file
mysqldump --all-databases -u root --password="$1" > backup.sql

# Create the compressed archive
tar -czvf "$backup_date.tar.gz" backup.sql

# Remove the MySQL dump file
rm backup.sql

echo "MySQL backup has been created and compressed as $backup_date.tar.gz"
