#!/usr/bin/env bash
# Bash script that diplays hours: 0to12, minutes 1to59

h=0
while [ "$h" -le 12 ]
do
    echo "Hour: $h"
    (( h++ ))

    m=1
    while [ "$m" -le 59 ]
    do
	echo "$m"
	(( m++ ))
    done
done
