#!/usr/bin/env bash
# Nginx is running as the nginx user.

# Set user and group for Nginx process
sed -i 's/^user.*$/user nginx;/g' /etc/nginx/nginx.conf

# Set Nginx to listen on all IPs on port 8080
sed -i 's/listen .*$/listen 0.0.0.0:8080;/g' /etc/nginx/sites-available/default

# Restart Nginx service with new configuration
pkill apache2
sudo -u nginx service nginx start
